# Generated by Django 5.1 on 2024-10-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_teacher_bio_remove_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('game', 'Game'), ('test', 'Test')], default='test', max_length=10),
        ),
    ]
