# Generated by Django 5.1 on 2024-10-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('IT', 'IT')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
