# Generated by Django 5.1 on 2024-11-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('IT', 'IT'), ('German', 'German')], max_length=10),
        ),
    ]
