# Generated by Django 5.1 on 2024-11-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('busy', 'Busy'), ('sleep', 'Sleep'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
