# Generated by Django 5.1 on 2024-11-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_picture.jpg', upload_to='profile_pictures/'),
        ),
    ]
