# Generated by Django 5.1 on 2024-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_picture', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('sleep', 'Sleep')], default='offline', max_length=10),
        ),
    ]
